version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ~/mosquitto/config:/mosquitto/config
      - ~/mosquitto/logs:/mosquitto/log