version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: Asia/Bangkok
    ports:
      - '5432:5432'
    volumes:
      - ./my-db:/var/lib/postgresql/data